### ISSUE TITLE
运行载入config.yaml文件时，总是提示[error] unmarshal yaml type config file error: yaml: line 24: did not find expected key

### ISSUE THREAD

**Issue by tomeleon** [imshuai/AlistAutoStrm#8]
使用的例子里面的yaml文件，只修改了本地目录映射地址和alist的用户信息，但是始终这个提示无法运行。

**Comment by tomeleon** [comment]
database: "strm.db"
loglevel: "info"
timeout: 30
create-sub-directory: true
exts:
  - ".mp4"
  - ".mkv"
  - ".avi"
  - ".rmvb"
  - ".ts"
  - ".wmv"
  - ".rm"
alt-exts:
  - ".jpg"
  - ".nfo"
  - ".srt"
  - ".ass"
endpoints:
  - base-url: "http://xxxx:xxxx"
    token: "alist-xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    username: "xxxxx"
    password: "xxxxxxxxxxxxxx"
    inscure-tls-verify: false
    dirs:
     - local-directory: "F:\\strm"
        remote-directories:
          - "/xxx/xxx"
        create-sub-directory: true
        not-recursive: false
        force-refresh: false
        disabled: false
    max-connections: 1

**Comment by tomeleon** [comment]
下载使用的windows的exe文件执行

**Comment by v2up-lee** [comment]
```yaml
database: "strm.db"
loglevel: "info"
timeout: 30
create-sub-directory: true
exts:
  - ".mp4"
  - ".mkv"
  - ".avi"
  - ".rmvb"
alt-exts:
  - ".jpg"
  - ".nfo"
  - ".srt"
  - ".ass"
endpoints:
  - base-url: "http://alist.cn"
    token: "alist-#####"
    username: "test"
    password: "test"
    inscure-tls-verify: false
    dirs:
      - local-directory: "data/movie"
        remote-directories:
          - "/path/to/movie"
        create-sub-directory: true
        not-recursive: false
        force-refresh: false
        disabled: false
    max-connections: 10
```
我使用这份配置，能够正确运行并获取到媒体信息，建议你再仔细检查下配置文件。
